### ISSUE TITLE
Off topic

### ISSUE THREAD

**Issue by rbatukaev** [aykamko/tag#10]
I am very sorry for off topic, but what is the name of terminal appliction on the main screenshot?

**Comment by aykamko** [comment]
I'm running iTerm2 on Mac OSX. I use `zsh` as my shell and [vim-hybrid](https://github.com/w0ng/vim-hybrid) as my colorscheme. You can check out my [dotfiles](https://github.com/aykamko/dotfiles) for more details but they're not too documented.
