### ISSUE TITLE
Binary downloads in the releases

### ISSUE THREAD

**Issue by dmarcoux** [aykamko/tag#11]
Hey!

It would be great to have binaries available to download directly in the releases. I want to package `tag` for my Linux distribution and it would make it a lot easier to do so. Go makes it quite simple to generate binaries for all platforms. As of right now, one must have Go to be able to install `tag`. The `Makefile` doesn't work either as it doesn't install dependencies.

Thanks for your work on `tag`.

**Comment by aykamko** [comment]
Alright, [binaries will be generated for 1.1.0 and onwards](https://github.com/aykamko/tag/releases/tag/1.1.0)! Let me know if anything is broken.
