### ISSUE TITLE
[suggestion] Submit to 'official' Homebrew

### ISSUE THREAD

**Issue by zx8** [aykamko/tag#15]
I'm sure Homebrew would accept the formula -- why maintain a separate tap?

**Comment by aykamko** [comment]
Good idea 👍

**Comment by NightMachinary** [comment]
@aykamko Please change the binary's name, it conflicts with a bottle already in Homebrew. This makes using it quite hard. `tag-ag` is perfectly fine. People can alias it to tag if they so wish.
