### ISSUE TITLE
Support for multiple editors/prefixes

### ISSUE THREAD

**Issue by zx8** [aykamko/tag#16]
Right now it's only possible to configure a single set of `TAG_ALIAS_PREFIX`s and `TAG_CMD_FMT_STRING`s. It would be really useful if this concept could be extended to allow the use of multiple editors. For example, I could configure `tag` such that `a23` would open in Atom, `v23` in vim, `s23` in Sublime Text, and so on.

The editor I choose to open the search results of `ag` with really depends on the type results I get / what I'm searching for.

**Comment by THuRStoN** [comment]
atom doesn't seem to accept atom {{filename}} +{{line_number}} I was trying to modify the TAG_CMD_FMT_STRING to use atom too. It'd an interesting feature for tag.

**Comment by grindhold** [comment]
:+1: 

I want to use tag from inside vim. I suggest the following
Check if the tag process is running as child of another known process (e.g. vim, emacs, Atom, [your favorite obscure hipster editor here]). For supported editors, we keep a mapping in the code that maps the editors process name to a TAG_CMD_FORMAT_STRING. Depending on what parent process has been detected, we write the according values to the alias-file. This would have the advantage, that we could use tag from the shell as well as from inside our favorite editors.

**Comment by aykamko** [comment]
Hey @zx8, I think your problem can we solved with a bash function. For example:
```
case "$3" in
  v) vim "$1" "+$2";;
  n) nvim "$1" "+$2";;
  s) subl "$1:$2";;
  a) atom "$1:$2";;
  *)
    echo "unrecognized editor: $3"
    exit 1;;
esac
```
Combine the above with:
```
export TAG_CMD_FMT_STRING='blah "{{.Filename}}" "{{.LineNumber}}"'
```

Should give you what I think you're asking for. Let me know if that works! I'll close this issue for now.
