### ISSUE TITLE
Not compatible prior to ag==0.25.0

### ISSUE THREAD

**Issue by myshen** [aykamko/tag#18]
Not really an issue, just for future reference.

The `--null` flag doesn't exist for the silver searcher until [0.25.0](https://github.com/ggreer/the_silver_searcher/pull/477/commits)

**Comment by aykamko** [comment]
Yeah, this was mentioned in https://github.com/aykamko/tag/issues/9
I should probably mention this in the README somewhere, thanks.

Will close this soon.

**Comment by aykamko** [comment]
8d2126cc76dd4b4b1e4225e64b763b8c7ee55374
