### ISSUE TITLE
Searching bootstrap.css.map freezes tag

### ISSUE THREAD

**Issue by jcassee** [aykamko/tag#19]
The `tag` command freezes when I run it on [bootstrap.css.map](https://github.com/twbs/bootstrap/raw/master/dist/css/bootstrap.css.map). I am running tag commit efa3eff1d39f23dcdfba90f013e9bac79d31421e and ag version 0.31.0 on Ubuntu 16.04. My shell is zsh 5.1.1. The problem disappears if I pipe to `cat`, i.e. `tag foo bootstrap.css.map | cat`.

Is there anything else I can do to help debug this problem?

**Comment by aykamko** [comment]
Hmm, it seems like the root of the problem might be in [vanilla ag](https://github.com/ggreer/the_silver_searcher). Try filing an issue there? Closing this issue for now because I think it's beyond my control.
