### ISSUE TITLE
syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by oren** [aykamko/tag#2]
adding this to .bashrc
```bash
if hash ag 2>/dev/null; then
  tag() { command tag "$@"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null }
  alias ag=tag
fi
```

show me the this error:
```
bash: /home/oren/.bashrc: line 58: syntax error near unexpected token `fi'
bash: /home/oren/.bashrc: line 58: `fi'
```

I am on ubuntu 15.10 in case it matters

**Comment by myggul92** [comment]
Add semicolon like below. then works.

    tag() { command tag "$@"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null }
    =>
    tag() { command tag "$@"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null ; }

**Comment by KyleAMathews** [comment]
Had the same problem on Mac OSX.
