### ISSUE TITLE
spaces/parens in filename seems to break tag

### ISSUE THREAD

**Issue by Alok** [aykamko/tag#21]
My search was in a file called 

```
~/writing/Journal Entry 2016-07-18 (Monday, July 18, 2016).md
```

I got the error:

```
no matches found: (Monday, July 18, 2016).md
```

I then typed `alias e1` and got this (home directory replaced with `~` for anonymity):

```
e1 is an alias for nvim ~/writing/Journal Entry 2016-07-18 (Monday, July 18, 2016).md +11
```

**Comment by andylima** [comment]
It's breaking for me, too.

**Comment by aykamko** [comment]
Fixed by https://github.com/aykamko/tag/pull/24

Sorry for the delay!
