### ISSUE TITLE
Support pt

### ISSUE THREAD

**Issue by kohlerm** [aykamko/tag#22]
I have interest in pt support :-)
I provided a pull request for pt to support the --null option, which as accepted. 
The latest release of pt https://github.com/monochromegane/the_platinum_searcher/releases 
is therefore compatible with ag with regards to tag.
See my fork at https://github.com/kohlerm/tag which works with pt. 
Would be cool to get pt support configurable for tag.

**Comment by aykamko** [comment]
@kohlerm Just checked out your fork, looks solid! Can you make a PR to this repo? I'd be happy to merge!

My only request is that the `ag` vs. `pt` choice should be configurable.

**Comment by kohlerm** [comment]
Sure any suggestion for the name of  an environment variable?

**Comment by aykamko** [comment]
how about `TAG_PROG`? feel free to choose something else if you think you have a better name

**Comment by aykamko** [comment]
closing this since I've added ripgrep support (https://github.com/aykamko/tag/pull/40)

**Comment by kohlerm** [comment]
switched to ripgrep in the meantime as well, so that's fine with me :smile:
