### ISSUE TITLE
Support -g flag

### ISSUE THREAD

**Issue by YPCrumble** [aykamko/tag#23]
Love the product - I've been using this a lot. Thanks for building it!

One feature that would be nice is to be able to use `ag -g text_in_filename` and then have the tagged files easily available to open via tags, rather than having to use autocomplete from the command line.

**Comment by aykamko** [comment]
@YPCrumble this sounds like a reasonable feature but I don't have the bandwidth to build it out. I'd be more open to incorporating this feature if you made a PR to this repo, but it would have to be non-breaking, i.e. I don't think we can change the behavior of `TAG_CMD_FMT_STRING` too much.

This last part makes it tricky to build this feature. :( I'm closing this Issue for now, feel free to re-open if you'd like to escalate.

**Comment by YPCrumble** [comment]
@aykamko I'd love to take a stab at this and have a little time. My hypothesis is I could just set line number to one when ag returns a path rather than a line of code. This would mean not having to break `TAG_CMD_FMT_STRING`.

I would need a little help getting set up. Happy to compile what you teach me into a CONTRIBUTING.md if that's helpful too.

Basically, what would be the steps to getting a local version of tag working on my machine? Sorry if this is too broad, I'm not super familiar with Go yet.
