### ISSUE TITLE
Use `$EDITOR` instead of `vim`

### ISSUE THREAD

**Issue by Hywan** [aykamko/tag#26]
Hello :-),

I recently moved from Vim to Emacs + Evil mode and I realized that tag is using `vim` (in a hardcode way). Would it be difficult to use `$EDITOR` instead please?

**Comment by aykamko** [comment]
You should be able to very easily configure what alias tag puts out with `TAG_CMD_FMT_STRING`. It's generalized to any editor. [Instructions here!](https://github.com/aykamko/tag#configuration)

**Comment by Hywan** [comment]
Thanks :-).
