### ISSUE TITLE
Support for ripgrep

### ISSUE THREAD

**Issue by kevinjalbert** [aykamko/tag#27]
I recently saw `ripgrep` pop up as the new [fast search tool](https://github.com/BurntSushi/ripgrep#quick-example-comparing-tools). I see that #22 is considering adding support for `pt`, via possibly a `TAG_PROG` environment variable.

I haven't looked too deeply into the format differences between `ag` vs `ripgrep`. I figure I could make the issue incase someone wants to take a stab at it?

**Comment by aykamko** [comment]
I've actually been wanting to `ripgrep` support lately too. I don't have much bandwidth to implement it myself right now, but I'll probably have some time around Thanksgiving (so end of November-ish).

Thanks for making this issue! Hopefully someone else can jump on it before I can. :)

**Comment by andylima** [comment]
I'm really looking forward to this getting in, too.  👍

**Comment by joaosa** [comment]
I'm also pretty interested in this too :)

**Comment by aykamko** [comment]
Starting work on this today, hoping to get this out before xmas!

**Comment by YPCrumble** [comment]
@aykamko I'd be happy to update my PR #30 to also work using the `--files` flag for ripgrep which I think would be the equivalent scenario.

**Comment by joaosa** [comment]
@aykamko any news on this? :)

**Comment by gwerbin** [comment]
FYI: https://github.com/BurntSushi/ripgrep/issues/89

**Comment by aykamko** [comment]
finally got around to this: https://github.com/aykamko/tag/pull/40

will be updating the docs and making a new release today. will close this issue after that.

**Comment by aykamko** [comment]
Done: https://github.com/aykamko/tag/releases/tag/1.4.0

**Comment by kevinjalbert** [comment]
@aykamko I wonder if the brew tap should be updated to account for new releases (brew tap is pointing to 1.2.1 still).

https://github.com/aykamko/homebrew-tag-ag/blob/master/tag-ag.rb#L1

**Comment by aykamko** [comment]
@kevinjalbert yup, gonna update this now

**Comment by aykamko** [comment]
brew tap is updated 😁
