### ISSUE TITLE
Filename incorrect when `-C` option used

### ISSUE THREAD

**Issue by sublimino** [aykamko/tag#29]
`ag -C n` where n is number breaks the alias creation

```
$ ag -C 1 wget
script/download.sh
18- echo "Downloading..."
[1] 19: wget foo.com
20-fi

$ type e1
e1 is aliased to `vim /usr/src/development_environment/18 +19'
```

The alias should point to `vim /usr/src/development_environment/script/download.sh +19` instead

**Comment by aykamko** [comment]
closing because this is more or less a duplicate of https://github.com/aykamko/tag/issues/35
