### ISSUE TITLE
Fails for single quotes in filename

### ISSUE THREAD

**Issue by Alok** [aykamko/tag#33]
If my file is named `'file with quotes'`, `tag` fails to escape it correctly.

**Comment by aykamko** [comment]
Yeah, this is definitely a limitation, but I figured it as a pathological edge case. I can't think of any reason why someone would want to have a single quote in their filename.  ¯\_(ツ)_/¯ 

That being said, if you want to open a PR to fix this edge case, be my guest. 😋
