### ISSUE TITLE
Use version tags compatible with gopkg.in

### ISSUE THREAD

**Issue by TheLonelyGhost** [aykamko/tag#34]
Though I'm sure the master branch is stable most times, I would prefer the ability to specify a version of the go package I'm installing when I install this. In order to do so, tags would have to be converted from `[Major].[Minor].[Patch]` syntax to `v[Major].[Minor].[Patch]`.

Existing tags can remain, but having a tag starting with `v` allows me to use gopkg.in to specify a version with the current version of go and `go get`.

Full instructions on gopkg.in can be found on their website: http://labix.org/gopkg.in

**Comment by aykamko** [comment]
👌 doing this now

**Comment by aykamko** [comment]
Done, I'll stick with prefixing `v` in the future, thanks for the heads up
