### ISSUE TITLE
Inconsistent release naming

### ISSUE THREAD

**Issue by dmarcoux** [aykamko/tag#42]
Hey!

I'm maintaining a package for tag on Arch Linux and I noticed that the new release is inconsistent with previous release. It should have been 1.4.0 instead of v1.4.0.

**Comment by aykamko** [comment]
Hey, I must have accidentally deleted the `1.4.0` tag, just pushed it back up, my mistake!

However, from `1.4.0` and onwards I'll be prepending a `v` to the version number to support http://labix.org/gopkg.in (https://github.com/aykamko/tag/issues/34).

**Comment by aykamko** [comment]
Thanks for maintaining the Arch package btw! ❤️
