### ISSUE TITLE
aur package gone

### ISSUE THREAD

**Issue by McKean** [aykamko/tag#45]
are we not supposed to use this anymore?
if not any reasons the aur package is gone? https://aur.archlinux.org/packages/tag-ag/

**Comment by aykamko** [comment]
@dmarcoux set up the `aur` package for this. Any update?

**Comment by dmarcoux** [comment]
I haven't used Arch Linux for more than 2 years now. A few months after this migration, I stopped maintaining the `tag-ag` package, thus making it an orphan package. If I remember correctly, someone took over. I don't know what happened next.

Anyway, it's not all lost. The last package version I created is in the following repository if you want to recreate it: https://github.com/dmarcoux-archives/tag-ag. There are instructions in the README under the [Package Maintenance section](https://github.com/dmarcoux-archives/tag-ag#package-maintenance).

**Comment by McKean** [comment]
@dmarcoux many thanks for the well documented flow. I forked your repo and resurrected the aur package https://aur.archlinux.org/packages/tag-ag/
Let me know if there are any issues. Thanks for the nice wrapper, I'm happy I can use this again!
