### ISSUE TITLE
Support other editors

### ISSUE THREAD

**Issue by bitwisecook** [aykamko/tag#5]
For example, Sublime Text

subl my_file:10

to jump to line 10 of my_file

**Comment by kevinjalbert** [comment]
You should be able to add the following export to your `.zshrc`/`.bashrc` file:
  `export TAG_CMD_FMT_STRING="subl {{.Filename}}:{{.LineNumber}}"`

I had to do this so that I would be using `nvim` instead of the default `vim`.

**Comment by aykamko** [comment]
Indeed like @kevinjalbert please read https://github.com/aykamko/tag#configuration

Should be very easy to use this for Sublime Text!
