### ISSUE TITLE
which e1 shows nothing

### ISSUE THREAD

**Issue by oren** [aykamko/tag#8]
After I run the tag command the file /tmp/tag_aliases have the correct aliases but `which e1` shows nothing and I have to run `source /tmp/tag_aliases` to make it work.

my .bashrc have:
```bash
if [ hash ag 2>/dev/null ]; then
	tag() { command tag "$@"; source ${TAG_ALIAS_FILE:-/tmp/tag_aliases} 2>/dev/null; }
	alias ag=tag
fi
```

**Comment by aykamko** [comment]
i think you need to drop the brackets on the first line:
`if [ hash ag 2>/dev/null ]; then` => `if hash ag 2>/dev/null; then`

**Comment by oren** [comment]
good idea. i tried it but it is still not working.

**Comment by aykamko** [comment]
hmm, I'm not sure what the problem is. what is your version of bash?

since you're not setting a custom `TAG_ALIAS_FILE`, try doing the following instead:
`tag() { command tag "$@"; source "/tmp/tag_aliases" 2>/dev/null; }`

worth a shot, let me know if it works.

**Comment by oren** [comment]
i get the same results - /tmp/tag_aliases have the correct aliases but it's not being sourced.

bash --version
```
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu
```

**Comment by oren** [comment]
works now. not sure what changed..thank you

**Comment by oren** [comment]
btw, `which e1` shows nothing but it's working
